version: '3.3'

# repo: https://github/ballab1/base_container.git
# containerOS: alpine i386-ubuntu

services:
    base:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: base_container
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS}:${OS_VERSION}
                TZ: "America/New_York"
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS}:${OS_VERSION}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: base_container
                version.cbf: $CBF_VERSION
        container_name: base
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${CONTAINER_TAG:-latest}
